server:
  port: ${port:8881}

xxl:
  job:
    admin:
      # xxl.job.admin.addresses
      addresses: http://192.168.200.128:8888/xxl-job-admin
    executor:
      # xxl.job.executor.appname
      appname: xxl-job-sharding-executor
      # xxl.job.executor.port
      port: ${executor.port:9999}